import { Geist, Geist_Mono } from "next/font/google";
import { renderToStaticMarkup } from "react-dom/server";
import RootLayout, { metadata } from "./layout";

jest.mock("next/font/google", () => ({
	Geist: jest.fn(() => ({ variable: "font-sans" })),
	Geist_Mono: jest.fn(() => ({ variable: "font-mono" })),
}));

describe("RootLayout (Server Component)", () => {
	test("フォントクラスを適用しつつ子要素を描画する", () => {
		const markup = renderToStaticMarkup(
			RootLayout({ children: <div data-testid="child">Content</div> }),
		);

		const mockGeist = Geist as jest.Mock;
		const mockGeistMono = Geist_Mono as jest.Mock;
		expect(mockGeist).toHaveBeenCalledWith({
			variable: "--font-geist-sans",
			subsets: ["latin"],
		});
		expect(mockGeistMono).toHaveBeenCalledWith({
			variable: "--font-geist-mono",
			subsets: ["latin"],
		});

		const dom = new DOMParser().parseFromString(markup, "text/html");
		const body = dom.body;
		expect(body.className).toBe("font-sans font-mono antialiased");
		expect(dom.querySelector('[data-testid="child"]')).not.toBeNull();
	});

	test("metadata をエクスポートしている", () => {
		expect(metadata.title).toBe("Create Next App");
		expect(metadata.description).toBe("Generated by create next app");
	});
});
